### PR TITLE
Compare package installed versions with desirable version via distutils.version.LooseVersion

### PR DESCRIPTION
**Pull request by grahamc**
I know this project is deprecated, but some tools still depend on it. While that is being sorted out, please merge this PR.

Fixes https://github.com/ContinuumIO/blz/issues/19

### CODE REVIEW

**Comment by mrocklin** [comment]
If there are no objections in 24 hours I plan to merge this.

@grahamc you probably already know this, but the project `bcolz` is an actively maintained fork of this project by the primary author under a different name.

**Comment by grahamc** [comment]
@mrocklin I do know that, thank you. Note that it has been 24 hours :) We're working to fully migrate away from blz, but this PR will still be useful.

**Comment by mrocklin** [comment]
Ah, quite.  My apologies for the delay.

**Comment by grahamc** [comment]
Thank you!

**Pull request merged**
